name: Ping App
on:
  schedule:
    - cron: '0 */2 * * *' # Pings every 6 hours
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit URL
        run: curl -I https://opamarketingnew.streamlit.app/
